apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - create
  - delete
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - watch
  - list
  - update
  - patch
  - create
  - delete