apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa
      containers:
      - image: {{ .Values.docker.registry }}/{{ .Values.docker.image.name }}:{{ .Values.docker.image.version }}
        imagePullPolicy: IfNotPresent
        name: {{ .Chart.Name }}-container
        ports:
        - containerPort: {{ .Values.docker.container.targetPort }}
        {{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        {{- end }}        
        env:
        - name: URLS
          value: {{ .Values.config.domains }}