apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.name }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-sa
  namespace: {{ .Values.namespace }}