apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}-sa
      containers:
      - name: {{ .Values.name }}
        image: public.ecr.aws/jotheesh-joe/custom/cert4k8s:{{ .Values.image.version }}
        env:
        - name: URLS
          value: {{ .Values.domains }}
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
