namespace: cert4k8s
docker:
  registry: ghcr.io/jotheesh-joe
  image:
    name: cert4k8s
    version: 1a6fb01a19a71c6e094ac6106eb90ce9c6afda0e
  container:
    targetPort: 80
deployment:
  replicas: 1
resources:
  requests:
    cpu: 200m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 16Gi
config:
  domains: dev.example.com, staging.example.com
