namespace: cert4k8s

docker:
  registry: ghcr.io/jotheesh-joe
  image:
    name: cert4k8s
    version: 4e3977f8c9c4c65e6a4b0e364b578e7b417a9724
  container:
    targetPort: 80

deployment:
  replicas: 1

resources:
  requests:
    cpu: 200m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 16Gi

config:
  domains: dev.example.com, staging.example.com
 
