# Default values for cert4k8s-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: cert4k8s

namespace: cert4k8s

image:
  version: 0.0.49
  secret: cert4k8s-imagepullsecret
  
# Give all the domains with comma separated
domains: ""
 
